name: cabrillo
description: "Cabrillo - Miniflux RSS reader"
publish_to: 'none'
version: "0.0.4" #version#

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  audio_service: 0.18.17
  audio_session: 0.1.25
  cached_network_image: ^3.3.1
  change_case: ^2.2.0
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  dynamic_color: ^1.7.0
  easy_image_viewer: ^1.5.1
  flutter_bloc: ^9.0.0
  flutter_widget_from_html: ^0.16.0
  flutter_cache_manager: ^3.3.2
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  hive_ce: ^2.10.1
  html: ^0.15.6
  http: ^1.2.1
  hydrated_bloc: ^10.0.0
  logger: ^2.5.0
  json_annotation: ^4.9.0
  just_audio: ^0.9.0
  nested: ^1.0.0
  path_provider: ^2.1.3
  relative_time: ^5.0.0
  rxdart: ^0.28.0
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  hive_ce_generator: ^1.8.2

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true